[package]
name = "firmware"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "1.0"
panic-halt = "1.0"
rp2040-hal = { version = "0.11", features = ["critical-section-impl"] }
ssd1306 = "0.10"
embedded-graphics = "0.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
